anchor_version = "0.24.2"

[programs.devnet]
metaplex_anchor_nft = "6Ag8EbK48mfb7MxMfsytNKa3veAJKXZXc1m9NNE3L5M7"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "ts-mocha --debug -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./deps/metadata.so"
