anchor_version = "0.24.2"

[programs.devnet]
metaplex_anchor_nft = "EKsCmywFjtZ6DABbi57qvqK2CBMjFsC7c3CXV3G2HfKs"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/flo/.config/solana/ds-4.json"

[scripts]
test = "ts-mocha --debug -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./deps/metadata.so"
