anchor_version = "0.19.0"

[programs.devnet]
metaplex_anchor_nft = "3niZhT5p3GizmMBQDSPWUXhFnkAAwfEZPD4xxnZpM2Fb"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/root/jerry3/test.json"

[scripts]
test = "ts-mocha --debug -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./deps/metadata.so"
